name: Polarisx
"on":
  push:
    branches:
      - main
      - master
      - develop
      - stage
      - release
  pull_request:
    branches:
      - main
      - master
      - develop
      - stage
      - release
  workflow_dispatch: {}
jobs:
  scan:
    steps:
      - name: Polaris Security Scan
        with:
          polaris_assessment_types: sca
          polaris_waitForScan: true
